name: dynamic_scaler
description: A Flutter package that enables dynamic scaling of widgets, images and padding
version: 0.0.1
author: Mayur Bhoi<mayur072000@gmail.com>
homepage: https://github.com/Mayur57/dynamic-scaler.git

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
